News:
  type: entity
  table: article
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    longdescription:
      type: text
      nullable: true
    title:
      type: string
      length: 255
      fixed: false
      nullable: false
    shortdescription:
      type: text
      nullable: false
    created:
      type: datetime
      nullable: false
    viewed:
      type: integer
      unsigned: false
      nullable: false
    commentId:
      type: integer
      unsigned: false
      nullable: false
      column: comment_id
    imageurl:
      type: string
      length: 100
      fixed: false
      nullable: true
    type:
      type: string
      length: 100
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
