nurix_bin_ajax_add_item:
    pattern: /add/ajax/{id}/
    defaults: { _controller: CatalogBundle:Bin:addAjaxBin }
    requirements:
      id:  \d+
    options:
      expose: true

nurix_bin_item:
    pattern: /
    defaults: { _controller: CatalogBundle:Bin:bin }

nurix_bin_bin_form:
    pattern: /bin-form/
    defaults: { _controller: CatalogBundle:Bin:binForm }

nurix_bin_main_widget:
    pattern: /widget/
    defaults: { _controller: CatalogBundle:Bin:mainBin }
    options:
      expose: true

nurix_bin_order_form:
    pattern: /checkout/
    defaults: { _controller: CatalogBundle:Bin:binOrderForm }

nurix_bin_delete_good:
    pattern: /delete/{id}/
    defaults: { _controller: CatalogBundle:Bin:remAjaxBin }
    requirements:
      id:  \d+
    options:
      expose: true