nurix_homepage:
    pattern:  /
    defaults: { _controller: NurixBundle:Home:home }

nurix_search:
    pattern:  /search/{search}
    defaults: { _controller: NurixBundle:Search:index }
    requirements:
        _method:  GET
nurix_ck_upload:
    pattern:  /cke/upload/
    defaults: { _controller: NurixBundle:Default:uploadFile }
