nurix_homepage:
    pattern:  /{_locale}
    defaults: { _controller: NurixBundle:Home:home, _locale:ru }
    requirements:
        _locale: en|ru|cn
    options:
        expose: true

nurix_ck_upload:
    pattern:  /cke/upload/
    defaults: { _controller: NurixBundle:Default:uploadFile }
