nurix_homepage:
    pattern:  /
    defaults: { _controller: NurixBundle:Home:home }

nurix_default:
    pattern:  /page/{name}
    defaults: { _controller: NurixBundle:Default:index }

nurix_search:
    pattern:  /search/
    defaults: { _controller: NurixBundle:Search:index }
    requirements:
        _method:  POST
