nurix_homepage:
    pattern:  /home
    defaults: { _controller: NurixBundle:Home:home }
nurix_default:
    pattern:  /default/{name}/
    defaults: { _controller: NurixBundle:Default:index,name:'Meder' }