parameters:
#    nurix.example.class: Nurix\NurixBundle\Example

services:
    nurix.menu_builder:
        class: Nurix\NurixBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    nurix.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: nurix.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    nurix.menu.sidebar:
        class: Knp\Menu\MenuItem
        factory_service: nurix.menu_builder
        factory_method: createSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time