parameters:
#    nurix.example.class: Nurix\NurixBundle\Example

services:
    nurix.menu_builder:
        class: Nurix\NurixBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory",@doctrine.orm.entity_manager]

    nurix.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: nurix.menu_builder
        factory_method: createMainMenu
        arguments: ["@request",@catalog.menu_builder]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu


    nurix.menu.info_sidebar:
            class: Knp\Menu\MenuItem
            factory_service: nurix.menu_builder
            factory_method: createBottomMenu
            arguments: ["@request"]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: bottom } # Named "sidebar" this time

    nurix.menu.info_sitemap:
            class: Knp\Menu\MenuItem
            factory_service: nurix.menu_builder
            factory_method: createSiteMapMenu
            arguments: ["@request"]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: info_sitemap } # Named "sidebar" this time


    nurix.search_form:
        class: Nurix\NurixBundle\Form\SearchType
        arguments: ["@translator"]



    nurix.twig.ceil_extension:
            class: Nurix\NurixBundle\Twig\CeilExtension
            tags:
                - { name: twig.extension }