sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                news:  { width: 190 , quality: 70}
        news:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 190 , quality: 95}
                big:   { width: 500 , quality: 90}
        goods:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.youtube

            formats:
                small: { width: 190 , quality: 95}
                big:   { width: 500 , quality: 90}
    cdn:
        server:
            path: /nurix/web/uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false