sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                goods_middle:   { width: 372 , height: 370, quality: 90}
                goods_original: { width: 650, quality: 80}
                goods_small: { width: 68, height: 60, quality: 80 }
                goods_92: { width: 92, height: 92, quality: 80 }
                goods_big: { width: 212, height: 192, quality: 80 }

        news:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 190 , quality: 95}
                big:   { width: 500 , quality: 90}

        slider:
            providers:
                - sonata.media.provider.image

            formats:
                standard: { width: 614, height: 300 , quality: 90}
        youtube:
            providers:
                - sonata.media.provider.youtube

            formats:
                default:  { width: 560}
    cdn:
        server:
            path: %media_upload_url% # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true
    providers:
        image:
            resizer:    sonata.media.resizer.custom # sonata.media.resizer.simple