Nurix\SliderBundle\Entity\Slider:
    type: entity
    table: slider
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        slider:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: Slider
    lifecycleCallbacks: {  }
