Nurix\SliderBundle\Entity\Slider:
    type: entity
    table: slider
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        active:
            type: boolean
            nullable: false
        title:
            type: string
            length: 120
            fixed: false
            nullable: false
        content:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
