Goods:
    type: entity
    table: goods
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        categoriyaId:
            type: integer
            unsigned: false
            nullable: false
            column: categoriyaId
        name:
            type: string
            length: 50
            fixed: false
            nullable: false
        alias:
            type: string
            length: 30
            fixed: false
            nullable: false
        shortDescription:
            type: text
            nullable: false
            column: shortDescription
        fullDesctiption:
            type: text
            nullable: false
            column: fullDesctiption
        price:
            type: decimal
            nullable: false
        imagePath:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: imagePath
    lifecycleCallbacks: {  }
