parameters:
#    catalog.example.class: Nurix\CatalogBundle\Example

services:
    catalog.model:
        class: Nurix\CatalogBundle\Model\CatalogModel
        arguments: [ @doctrine.orm.entity_manager ]

    catalog.menu_builder:
        class: Nurix\CatalogBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    catalog.menu.catalog_sidebar:
            class: Knp\Menu\MenuItem
            factory_service: catalog.menu_builder
            factory_method: createCatalogSideMenu
            arguments:  [@request, @catalog.model]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: catalog_sidebar } # Named "sidebar" this time

    catalog.twig.exchange_extension:
            class: Nurix\CatalogBundle\Twig\ExchangeExtension
            tags:
                - { name: twig.extension }

    catalog.twig.count_extension:
            class: Nurix\CatalogBundle\Twig\CountExtension
            tags:
                - { name: twig.extension }