parameters:
#    catalog.example.class: Nurix\CatalogBundle\Example

services:
    catalog.menu_builder:
        class: Nurix\CatalogBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    catalog.menu.catalog_sidebar:
            class: Knp\Menu\MenuItem
            factory_service: catalog.menu_builder
            factory_method: createCatalogSideMenu
            arguments:  [@request,@doctrine.orm.entity_manager]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: catalog_sidebar } # Named "sidebar" this time

    catalog.twig.exchange_extension:
            class: Nurix\CatalogBundle\Twig\ExchangeExtension
            arguments:
                  doctrine: "@doctrine"
            tags:
                - { name: twig.extension }

    catalog.twig.count_extension:
            class: Nurix\CatalogBundle\Twig\CountExtension
            tags:
                - { name: twig.extension }

    catalog.product.importparser:
            class: Nurix\CatalogBundle\Parser\Excel5Parser
            arguments: [@doctrine, @xls.load_xls5]

    catalog.product.google_parser:
        class: Nurix\CatalogBundle\Parser\GoogleParser
        arguments: [@sonata.media.manager.media,@sonata.media.manager.gallery,@sonata.media.entity_manager]

    catalog.product.goods_upload_parser:
        class: Nurix\CatalogBundle\Parser\GoodsUploadParser
        arguments: [@doctrine,@xls.load_xls5]

    catalog.menu.catalog_sitemap:
            class: Knp\Menu\MenuItem
            factory_service: catalog.menu_builder
            factory_method: createSiteMapMenu
            arguments:  [@request,@doctrine.orm.entity_manager]
            scope: request
            tags:
                - { name: knp_menu.menu, alias: catalog_sitemap }
